export { default as ThumbUpIcon } from './ThumbUp.svg';
export { default as ThumbDownIcon } from './ThumbDown.svg';
export { default as Flag } from './Flag.svg';
export { default as UpArrowLogo } from './UpArrowLogo.svg';
export { default as NextIcon } from './Next.svg';
export { default as EmptyAvatar } from './EmptyAvatar.svg';
export { default as XIcon } from './X.svg';
export { default as PlusIcon } from './Plus.svg';
export { default as ImageIcon } from './Image.svg';
